### PR TITLE
TOSCin extension

### PR DESCRIPTION
**Pull request by Rossojo**
Enhancing the instance retrieval to use multiple deployment technologies for one instance model.
Rename the edmm-instance module to TOSCin to match name in papers.

Only the edmm-instance model is renamed and changed. All other modules remain unchanged.

### CODE REVIEW

**Comment by miwurster** [comment]
Hey, could you please add a description to provide some info and background what this PR is about?

**Review by miwurster — CHANGES_REQUESTED** [review]
Remove this. Apply your IDE codestyle according to the checkstyle.xml.

**Comment by miwurster** [comment]
Please highlight in the description above what changes you have made to the other packages.

**Comment by Rossojo** [comment]
> 
> 
> Remove this. Apply your IDE codestyle according to the checkstyle.xml.

Sorry, what exactly do you mean by 'this'? Can't find any reference

**Comment by Rossojo** [comment]
> 
> 
> Please highlight in the description above what changes you have made to the other packages.

To which packages are you referring by 'other'?

**Comment by miwurster** [comment]
Hey, oh the GitHub review option didn't relate my comment properly. I meant the changes to the `.editorconfig`. Instead, please use an IDE config that just applies to the checkstyle file if possible (or use the codestyle for IntelliJ: https://github.com/UST-EDMM/edmm/tree/master/docs/codestyle).
 
With "other" I refer to other Maven modules of the project, i.e., edmm-cli, edmm-core, edmm-orchestration-ui, edmm-orchestration, and edmm-web.

**Comment by Rossojo** [comment]
Ok, I removed the `.editorconfig` and some other files. Also fixed import order.

Description is updated, all other modules remain unchanged.

**Review by miwurster — APPROVED** [review]

**Comment by miwurster** [comment]
Please note that I merged this PR with GitHub's squash-merge option. So if you further work on your fork, please make sure that you do a hard sync with the current master ;-)

**Pull request merged**
